name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Continuous Integration Check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 7

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Run ESLint
        run: pnpm lint

      - name: Build Applications
        run: pnpm build

      - name: Test Applications
        run: pnpm test
